sudo: required
services:
  - docker

before_install:
  - docker build -t sameerkamrandev/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true  sameerkamrandev/react-test npm test -- --coverage

after_success:
  - docker build -t sameerkamrandev/multi-client ./client 
  - docker build -t sameerkamrandev/multi-nginx ./nginx
  - docker build -t sameerkamrandev/multi-server ./server
  - docker build -t sameerkamrandev/multi-worker ./worker
  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to doceker hub
  - docker push sameerkamrandev/multi-client
  - docker push sameerkamrandev/multi-nginx
  - docker push sameerkamrandev/multi-server
  - docker push sameerkamrandev/multi-worker

  